[MODROLESKC-150]: fix loading reference data multiple times
folio-org/mod-roles-keycloak pull request #39
Opened 2024-02-20 10:17 UTC by yaroslav-kiriak

## Purpose
Fix loading reference data multiple times

## Approach
Role on the Keycloak side is created with new generated ID in any case, therefore check for existence is by role name

## TODOS and Open Questions

- [ ] Check logging

## Learning
Tested locally.

Before:
![image](https://github.com/folio-org/mod-roles-keycloak/assets/159446370/4a1651fb-cb60-436a-a843-13ea2ba99257)

After:
![image](https://github.com/folio-org/mod-roles-keycloak/assets/159446370/7e60b8d4-0259-4c8e-9d36-d701cd5cc7bb)

## Pre-Merge Checklist:

Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added, or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail? Which endpoints/schemas changed, etc.
  - [ ] Do they have all the appropriate links to blocked/related issues?
- Are the Rally stories under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be achieved, especially as the number of inter-module and
inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the
responsibility of the PR assignee.

2024-02-20 11:00 UTC, pfilippov-ebsco requested changes

2024-02-20 11:00 UTC, pfilippov-ebsco commented on src/test/java/org/folio/roles/integration/keyclock/KeycloakRoleServiceTest.java
> +    void positive_returns_empty_role_when_not_found() {
```suggestion
    void positive_returnsEmptyRoleWhenNotFound() {
```

2024-02-20 11:00 UTC, pfilippov-ebsco commented on src/test/java/org/folio/roles/integration/keyclock/KeycloakRoleServiceTest.java
> +    void negative_throws_keycloak_api_exception_while_feign_exception() {
```suggestion
    void negative_throwsKeycloakApiExceptionWhileFeignException() {
```

2024-02-20 12:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/mod-roles-keycloak?pullRequest=39) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/mod-roles-keycloak?pullRequest=39) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yaroslav-epam<br/>:x: yaroslav-kiriak<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/mod-roles-keycloak?pullRequest=39) it.</sub>

2024-02-21 09:51 UTC, OleksiiKuzminov approved these changes

2024-02-22 10:26 UTC, pfilippov-ebsco approved these changes

2024-02-22 11:15 UTC, merged